FROM docker.io/python:3-slim
COPY backend/requirements.txt /
RUN pip3 install --upgrade pip
RUN pip3 install -r /requirements.txt
WORKDIR /app
EXPOSE 8000
CMD ["gunicorn", "--config", "gunicorn_config.py", "wsgi:application"]